name: Main workflow
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 10.x
      - run: node ./common/scripts/install-run-rush.js check
      - run: node ./common/scripts/install-run-rush.js change --verify
      - run: node ./common/scripts/install-run-rush.js install
      - run: node ./common/scripts/install-run-rush.js rebuild --verbose
      - run: node ./common/scripts/install-run-rush.js test
